### ISSUE TITLE
The recent update to stdlib has broken PickerBlueprinter

### ISSUE THREAD

**Issue by credomane** [Nexela/PickerBlueprinter#10]
#### Describe the Bug
Factorio fails to load to the main menu
![image](https://user-images.githubusercontent.com/1283031/172026813-6186f791-73dc-4963-94bd-59c45dc22c36.png)

#### To Reproduce

Have the the mods stdlib, Picker Atheneum and Picker Blieprinter Enabled.

#### Save file & Username

Save not applicable. Issue appears during data state.

#### Log file

<details>
<summary>Factorio.log</summary>

   0.000 2022-06-04 17:05:20; Factorio 1.1.59 (build 59719, linux64, steam)
   0.061 Operating system: Linux (ManjaroLinux 21.2.6)
   0.061 Program arguments: "/home/credomane/.steam/debian-installation/steamapps/common/Factorio/bin/x64/factorio" 
   0.061 Read data path: /home/credomane/.steam/debian-installation/steamapps/common/Factorio/data
   0.061 Write data path: /home/credomane/.factorio [28258/169333MB]
   0.061 Binaries path: /home/credomane/.steam/debian-installation/steamapps/common/Factorio/bin
   0.066 System info: [CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz, 6 cores, RAM: 15933 MB]
   0.066 Environment: DISPLAY=:0 WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=plasma XDG_SESSION_DESKTOP=KDE XDG_CURRENT_DESKTOP=KDE __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
   0.066 Display options: [FullScreen: 0] [VSync: 0] [UIScale: custom (100.0%)] [Native DPI: 1] [Screen: 255] [Special: lmw] [Lang: en]
   0.364 Available displays: 2
   0.364  [0]: S2719DGF 27" - {[0,0], 2560x1440, SDL_PIXELFORMAT_RGB888, 144Hz}
   0.364  [1]: W2246 22" - {[2560,0], 1920x1080, SDL_PIXELFORMAT_RGB888, 60Hz}
   0.488 Initialised OpenGL:[0] NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2; driver: 3.3.0 NVIDIA 510.73.05
   0.488   [Extensions] s3tc:yes; KHR_debug:yes; ARB_clear_texture:yes, ARB_copy_image:yes
   0.488   [Version] 3.3
   0.488 Graphics settings preset: very-high
   0.488   Dedicated video memory size 6144 MB
   0.521 Graphics options: [Graphics quality: high] [Video memory usage: high] [DXT: high-quality] [Color: 32bit]
   0.521                   [Max threads (load/render): 32/6] [Max texture size: 0] [Tex.Stream.: 1] [Rotation quality: normal] [Other: STDCWT] [B:0,C:0,S:100]
   0.526 [Audio] Backend:default; Depth:16, Channel:2, Frequency:44100; MixerQuality:linear
   1.025 Loading mod settings PickerAtheneum 1.2.4 (settings.lua)
   1.025 Loading mod settings PickerBlueprinter 1.1.5 (settings.lua)
   1.027 Loading mod core 0.0.0 (data.lua)
   1.075 Loading mod base 1.1.59 (data.lua)
   1.259 Loading mod PickerAtheneum 1.2.4 (data.lua)
   1.331 Loading mod PickerBlueprinter 1.1.5 (data.lua)
   1.342 Error ModManager.cpp:1588: Failed to load mod "PickerBlueprinter": __PickerBlueprinter__/prototypes/bpprioritizer.lua:4: attempt to call field 'get_startup' (a nil value)
stack traceback:
	__PickerBlueprinter__/prototypes/bpprioritizer.lua:4: in main chunk
	[C]: in function 'require'
	__PickerBlueprinter__/data.lua:4: in main chunk
   1.344 Loading mod core 0.0.0 (data.lua)
   1.406 Checksum for core: 3123733693
   1.455 Error ModManager.cpp:1588: Error in assignID: recipe-category with name 'crafting' does not exist.

Source: default (utility-sprites).
   1.543 Initial atlas bitmap size is 16384
   1.543 Created atlas bitmap 2048x640 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
   1.543 Created virtual atlas pages 4096x4096x0
   1.550 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
   1.554 Parallel Sprite Loader initialized (threads: 5)
   1.577 Sprites loaded
   1.582 Generated mipmaps (5) for atlas [0] of size 2048x640   
   1.582 Custom mipmaps uploaded.
   1.589 Factorio initialised
</details>

**Comment by Nexela** [comment]
Should be fixed in the latest release. Thank you.
closed by aa1a6820f3bfcc2e8694bd03b0d8c969e62de509

**Comment by credomane** [comment]
That did the trick! Thanks.
